

//@version=5
strategy("练习-布林突破策略",
         overlay=true,
         initial_capital=4000,
         default_qty_type=strategy.percent_of_equity,
         backtest_fill_limits_assumption=1,
         default_qty_value=100,
         process_orders_on_close=true,
         commission_value = 0.04)


a = input(10,  'Percent K Length')
b = input(3,  'Percent D Length')
ob = input(40, 'Overbought')
os = input(-40, 'Oversold')

atrPeriod = input(100, title="ATR Period")
factor = input(30, title="ATR Factor")

[supertrend, direction] = ta.supertrend(factor, atrPeriod)


ll = ta.lowest(low, a)
hh = ta.highest(high, a)
diff = hh - ll
rdiff = close - (hh + ll) / 2

avgrel = ta.ema(ta.ema(rdiff, b), b)
avgdiff = ta.ema(ta.ema(diff, b), b)

SMI = avgdiff != 0 ? (avgrel / (avgdiff/2) * 100) : 0
SMIsigial = ta.ema(SMI, b)
emasigial = ta.ema(SMI, 10)

h0 = hline(40)
h1 = hline(-40)

where1 = ta.crossover(SMIsigial, -40)
where2 = direction < 0
where3 = ta.crossover(emasigial, SMIsigial)


if where1 and where2
    strategy.entry("long", strategy.long)
    takeProfit = strategy.opentrades.entry_price(0) * 1.02
    stopLoss = strategy.opentrades.entry_price(0) * 0.99
    strategy.exit("exit", "long", limit=takeProfit, stop=stopLoss, comment_loss='stop_loss',  comment_profit='take_profit')


if direction > 0
    strategy.close_all("趋势结束平仓")





