// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © openbox6
//@version=5
import openbox6/zhuang/29 as lz
strategy("奔波霸策略",
         overlay=true,
         initial_capital=2000,
         default_qty_type=strategy.percent_of_equity,
         default_qty_value=100,
         process_orders_on_close=true,
         commission_value = 0.04)


// 输入参数
startPeriodTime = input.time(timestamp('1 Jan 2021'), '开始', group='交易日期范围', inline='开始时间')
endPeriodTime = input.time(timestamp('31 Dec 2099'), '结束', group='交易日期范围', inline='结束时间')
isStartPeriodEnabledAndInRange = startPeriodTime <= time
isEndPeriodEnabledAndInRange = endPeriodTime >= time

// 移动止盈止损
stop_type = input.string("移动止盈", title="止盈止损方式", options=["移动止盈", "固定止盈"])

// 交易时间段
isInRange = isStartPeriodEnabledAndInRange and isEndPeriodEnabledAndInRange
input_leverage = input.float(1.5, title = "杠杆倍数", step = 0.5)
// 交易类型
tradeType = input.string("全部", title="交易方向", options=["全部", "只做多", "只做空"])
// 布林带参数
bullLength = input.int(20, title = '布林带长度')
bullMulti = input.float(2.0, title = '布林带倍数')
maLength = input.int(89, title = '趋势平均线长度')

// 乖离
guaili = (close - ta.ema(close, 8)) / ta.ema(close, 8) * 100


// ------------ vo指标 ----------------------
vo_group = 'VO指标参数'
length1 = input.int(7, title = 'Fast Length', group = vo_group)
length2 = input.int(14, title = 'Middle Length', group = vo_group)
length3 = input.int(28, title = 'Slow Length', group = vo_group)
average(bp, tr_, length) =>
    math.sum(bp, length) / math.sum(tr_, length)

high_ = math.max(high, close[1])
low_ = math.min(low, close[1])
bp = close - low
tr_ = high_ - low_

avg7 = average(bp, tr_, length1)
avg14 = average(bp, tr_, length2)
avg28 = average(bp, tr_, length3)
vo = 100 * (4*avg7 + 2*avg14 + avg28)/7


// 初始化上一次出场的bar索引
var lastExitBar = 0
// 止损百分比
st_pt_percent = 0.02
// 止盈百分比
st_p_percent = 0.02
// ##############################################################

// 布林带
[basis, upper, lower] = lz.getBooling(close, bullLength, bullMulti)
plot(basis, title = "中轨")
plot(upper, title = "上轨")
plot(lower, title = "下轨")

ma200 = ta.sma(close, maLength)
plot(ma200, title = '趋势平均线', color = color.yellow, linewidth = 2)

// 平均成交量
volSma = ta.sma(volume, 10)
// K线的实体
shiti = math.abs(close-open)
// 下影线
xy_xian = (close > open ? open : close) - low
// 上影线
sy_xian = high - (close > open ? close : open)

var long_bar = 0
var short_bar = 0

// long_signal = (guaili[1] >= 1.5 and guaili[1]<=3.5) and close[1] > upper[1] and close[1] > open[1] and close[0] > ((close[1]+open[1])/2) and upper > ma200
// short_signal = ((guaili[1] <= -1.3 and guaili[1]>=-3.5)) and close[1] < lower[1] and close[1] < open[1] and close[0] < ((close[1]+open[1])/2)

long_signal = close[1] > upper[1] and close[1] > open[1] and close[0] > ((close[1]+open[1])/2) and ta.crossover(vo, 65)
short_signal = close[1] < lower[1] and close[1] < open[1] and close[0] < ((close[1]+open[1])/2) and ta.crossunder(vo, 45)

// 收盘价突破上轨 && 最低价大于中轨 && 
if long_signal and isInRange and strategy.position_size == 0 and (bar_index - lastExitBar) > 10 and tradeType != '只做空'
    lastExitBar := bar_index
    long_bar := bar_index
    strategy.entry('做多', strategy.long, qty = input_leverage * strategy.equity / close[0], comment='突破做多')
    stop_loss = close - (upper[1] - basis[1])
    limit = close + (upper[1] - basis[1])
    strategy.exit('做多止损', '做多', stop = stop_loss, limit = limit, comment_profit='做多止盈', comment_loss='做多止损')
    

if short_signal and isInRange and strategy.position_size == 0 and (bar_index - lastExitBar) > 10 and tradeType != '只做多'
    lastExitBar := bar_index
    short_bar := bar_index
    strategy.entry('做空', strategy.short, qty = input_leverage * strategy.equity / close[0], comment='突破做空')
    stop_loss = close + (upper[1] - basis[1])
    limit = close - (upper[1] - basis[1])
    strategy.exit('做空止损', '做空', stop = stop_loss, limit = limit, comment_profit='做空止盈', comment_loss='做空止损')


if strategy.position_size > 0 and (bar_index - long_bar) > 20
    strategy.close('做多', comment = '做多超时平仓')


if strategy.position_size < 0 and (bar_index - short_bar) > 20
    strategy.close('做空', comment = '做空超时平仓')



// if stop_type == '固定止盈'
//     strategy.exit('做空止损', '做空', stop = strategy.position_avg_price * (1 + st_pt_percent), limit = strategy.position_avg_price * (1 - st_p_percent), comment_profit='做空止盈', comment_loss='做空止损')
//     strategy.exit('做多止损', '做多', stop = strategy.position_avg_price * (1 - st_pt_percent), limit = strategy.position_avg_price * (1 + st_p_percent), comment_profit='做多止盈', comment_loss='做多止损')

// if stop_type == '移动止盈'
//     strategy.exit('做多平仓', '做多', stop = strategy.position_avg_price * (1 - st_pt_percent), trail_points = strategy.position_avg_price * st_p_percent / syminfo.mintick, trail_offset = strategy.position_avg_price * 0.002 / syminfo.mintick, comment_profit='做多止盈', comment_loss='做多止损', comment_trailing="移动止盈")
//     strategy.exit('做空平仓', '做空', stop = strategy.position_avg_price * (1 + st_pt_percent), trail_points = strategy.position_avg_price * st_p_percent / syminfo.mintick, trail_offset = strategy.position_avg_price * 0.002 / syminfo.mintick)

// if strategy.position_size > 0 and guaili <= -1
//     strategy.close('做多', comment = '做多乖离平仓')

// if strategy.position_size < 0 and guaili >= 1
//     strategy.close('做空', comment = '做空乖离平仓')









